[phases.setup]
nixPkgs = ["jdk17"]

[phases.install]
cmds = ["./mvnw clean package -DskipTests"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "java -jar target/pulsetap-backend-0.0.1-SNAPSHOT.jar"
